eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    eureka-service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true
