# Eureka Client Service Configurations
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
